### ISSUE TITLE
Public protocol mock should have a public default initializer

### ISSUE THREAD

**Issue by lutes1** [MetalheadSanya/swift-mock#45]
A public protocol mock has no public default initializer hence it's impossible to create it from outside of the module it was originally defined.

<img width="809" alt="image" src="https://github.com/MetalheadSanya/swift-mock/assets/19331105/a66c623f-9dcc-4255-a957-6105a8dfabc2">

P.S. Thank you for such an amazing library!

**Comment by MetalheadSanya** [comment]
Thank you for bug report. You can find fix in release 0.6.1
