### ISSUE TITLE
Point verify failure to `verify` call

### ISSUE THREAD

**Issue by doobnet** [MetalheadSanya/swift-mock#57]
If one sets `testFailureReport` to `{ XCTFail($0) }` and `verify` fails the test, there's no clear indication of why the test failed. One needs to go to the Issue navigator in Xcode to see the exact failure. It would be nice if the test failure pointed to the call to `verify` in the test.

**Comment by MetalheadSanya** [comment]
Thx for reporting. I'll fix this on the next release.

**Comment by MetalheadSanya** [comment]
Expecting changes:

1. Append to each method of `Verify` structure additional arguments: `file` with default value `#filePath`, `line` with default value `#line`.
2. Append to `verify` method of `VerifyContainer` additional arguments: `file` and `line`
3. Pass `file` and `line` to from `Verify` struct method to `VerifyContainer`.
4. **Breaking Changes**: append to `testFailureReport` two additional arguments, `file` and `line`.
5. Pass in `VerifyContainer` `file` and  `line` arguments to `testFailureReport`.
