### ISSUE TITLE
Add support for @Mock to extension of a protocol 

### ISSUE THREAD

**Issue by nicofrancken** [MetalheadSanya/swift-mock#64]
To enable clean separation of testing and production code it would be nice to be able to place @Mock on an extension of a protocol.

Production code:
protocol MyAwesomeProtocol {
 func doAmazingThings()
}

Test code:
@Mock
extension  MyAwesomeProtocol {}

This will add the MyAwesomeProtocolMock in the testing code instead of the production code.

**Comment by MetalheadSanya** [comment]
Unfortunately, the macro only knows about the declaration it is attached to. Even if 2 declarations are in the same file, you can find out which child declarations are in the declaration to which the macro was attached. This is a limitation of how macros work

**Comment by MetalheadSanya** [comment]
In the example above, there are no child declarations in the extension. The macro simply does not know what declarations are in the protocol and will not be able to generate anything
